#!/usr/bin/env bash
# #284: refresh the pinned semgrep ruleset and show what changed.
#
# The ruleset is a git submodule (.semgrep/rules → semgrep/semgrep-rules at one
# commit) plus a manifest (.semgrep/rules.tsv) naming the rule files that made up
# the registry's c/auto response. The rules themselves are never committed here:
# they are under the Semgrep Rules License v1.0, which forbids redistribution.
#
# Usage: bash scripts/semgrep-refresh-rules.sh [<semgrep-rules commit>]
#   default commit: current upstream default branch head (develop)
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RULES_DIR="$ROOT/.semgrep/rules"
MANIFEST="$ROOT/.semgrep/rules.tsv"
README="$ROOT/.semgrep/README.md"
WANT="${1:-}"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/semgrep-refresh.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

# 1. move the submodule to the requested commit
git -C "$ROOT" submodule update --init --depth 1 -- .semgrep/rules >/dev/null
if [[ -n "$WANT" ]]; then
  git -C "$RULES_DIR" fetch -q --depth 1 origin "$WANT"
  git -C "$RULES_DIR" checkout -q "$WANT"
else
  git -C "$RULES_DIR" fetch -q --depth 1 origin HEAD
  git -C "$RULES_DIR" checkout -q FETCH_HEAD
fi
COMMIT="$(git -C "$RULES_DIR" rev-parse HEAD)"
COMMIT_DATE="$(git -C "$RULES_DIR" log -1 --format=%cs)"

# 2. fetch the registry's current c/auto rule ids (ids only; the response is not kept)
curl -fsSL "https://semgrep.dev/c/auto" -o "$TMP/auto.yml"
grep -E '^- id:' "$TMP/auto.yml" | sed 's/^- id: //' | sort | uniq >"$TMP/new_ids.txt"
grep -v '^#' "$MANIFEST" | cut -f1 | sort | uniq >"$TMP/old_ids.txt" || true

# 3. resolve every id to its rule file. A registry id is the rule file's path
#    (dots for slashes, no extension) followed by the rule's own id, and
#    validate.sh enforces exactly that relationship, so no prefix search.
#    Registry ids are lower-cased while a few upstream files are not
#    (X509-…yaml), so the path is looked up case-insensitively in the
#    submodule's index and the manifest records the exact spelling — a
#    case-insensitive filesystem would otherwise produce a manifest that
#    only resolves on macOS.
: >"$TMP/mapped.tsv"; : >"$TMP/unmapped.txt"
while IFS= read -r id; do
  leaf="${id##*.}"
  rel="${id%.*}"; rel="${rel//.//}"
  hit=""
  for ext in .yaml .yml; do
    actual="$(git -C "$RULES_DIR" ls-files -- ":(icase)$rel$ext" | head -n1)"
    if [[ -n "$actual" ]] && grep -qE "^[[:space:]]*(-[[:space:]]*)?id:[[:space:]]*(${leaf}|${id})[[:space:]]*$" "$RULES_DIR/$actual"; then
      hit="$actual"; break
    fi
  done
  if [[ -n "$hit" ]]; then printf '%s\t%s\n' "$id" "$hit" >>"$TMP/mapped.tsv"; else echo "$id" >>"$TMP/unmapped.txt"; fi
done <"$TMP/new_ids.txt"

echo "submodule: $COMMIT ($COMMIT_DATE)"
echo "c/auto rule ids: $(wc -l <"$TMP/old_ids.txt" | tr -d ' ') (manifest) -> $(wc -l <"$TMP/new_ids.txt" | tr -d ' ') (registry); $(wc -l <"$TMP/mapped.tsv" | tr -d ' ') resolve to files in semgrep/semgrep-rules"
echo "--- removed rule ids:"; comm -23 "$TMP/old_ids.txt" "$TMP/new_ids.txt" || true
echo "--- added rule ids:";   comm -13 "$TMP/old_ids.txt" "$TMP/new_ids.txt" || true
echo "--- registry ids with no file in semgrep/semgrep-rules (not part of the gate):"
cat "$TMP/unmapped.txt"
# Unresolved ids are dropped from the gate, so they must be ones we have looked
# at and chosen to drop: today that is only trailofbits.* (AGPL-3.0, Go/Python,
# a different repository). Anything else means the resolver or the upstream
# layout changed — stop rather than silently shrink the gate.
if grep -vqE '^trailofbits\.' "$TMP/unmapped.txt"; then
  echo "refresh aborted: registry ids outside the known-unresolvable set (trailofbits.*) did not resolve to a file — inspect before re-running:" >&2
  grep -vE '^trailofbits\.' "$TMP/unmapped.txt" >&2
  exit 1
fi

# 4. rewrite the manifest and the README table
TODAY="$(TZ=UTC date +%Y-%m-%d)"
{
  printf '# semgrep rule manifest — generated by scripts/semgrep-refresh-rules.sh; do not hand-edit.\n'
  printf '# registry: https://semgrep.dev/c/auto  snapshot: %s  submodule: %s\n' "$TODAY" "$COMMIT"
  printf '# <registry rule id>\t<rule file inside .semgrep/rules>\n'
  sort "$TMP/mapped.tsv"
} >"$MANIFEST"
python3 - "$README" "$TODAY" "$COMMIT" "$COMMIT_DATE" "$(wc -l <"$TMP/mapped.tsv" | tr -d ' ')" "$(wc -l <"$TMP/unmapped.txt" | tr -d ' ')" <<'PY'
import re, sys
readme, today, commit, cdate, mapped, unmapped = sys.argv[1:]
text = open(readme).read()
text = re.sub(r"\| Snapshot date \| [^|]+\|", f"| Snapshot date | {today} |", text)
text = re.sub(r"\| Pinned commit \| [^|]+\|", f"| Pinned commit | `{commit}` ({cdate}) |", text)
text = re.sub(r"\| Rules in manifest \| [^|]+\|", f"| Rules in manifest | {mapped} (registry ids with no upstream file: {unmapped}) |", text)
open(readme, "w").write(text)
PY
echo "updated .semgrep/rules.tsv, .semgrep/README.md and the submodule pointer — stage .semgrep/rules too, re-run the whole-repo parity scan (see README) and record it in the PR."
